# Generated by Django 5.2.18 on 2026-10-06 16:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual')], default='Monthly', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('max_promo_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BranchPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Hamra', 'Hamra'), ('Achrafieh', 'Achrafieh'), ('Jnah', 'Jnah'), ('Zalka', 'Zalka')], max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('discount_type', models.CharField(choices=[('Percent', 'Percent'), ('Fixed', 'Fixed amount')], default='Percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to='administration.staffaccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='plans.membershipplan')),
            ],
            options={
                'ordering': ['-start_date', 'id'],
            },
        ),
    ]
