# Generated by Django 5.2.17 on 2026-10-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('permissions', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('job_title', models.CharField(choices=[('System Administrator', 'System Administrator'), ('General Manager', 'General Manager'), ('Branch Manager', 'Branch Manager'), ('Receptionist', 'Receptionist'), ('Coach', 'Coach'), ('Marketing Staff', 'Marketing Staff')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_accounts', to='administration.role')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
