# Generated by Django 5.2.17 on 2026-10-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Frozen', 'Frozen'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('branch', models.CharField(choices=[('Hamra', 'Hamra'), ('Achrafieh', 'Achrafieh'), ('Jnah', 'Jnah'), ('Zalka', 'Zalka')], max_length=30)),
                ('membership_plan', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Basic', max_length=20)),
                ('join_date', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
