# Generated by Django 5.2.17 on 2026-10-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_name', models.CharField(max_length=150)),
                ('health_disclaimer_accepted', models.BooleanField(default=False)),
                ('liability_waiver_accepted', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiver', to='members.member')),
            ],
        ),
    ]
