# Generated by Django 5.2.17 on 2026-10-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_password_hash_member_username'),
        ('members', '0002_waiver'),
    ]

    operations = [
    ]
